version: '3.8'

services:
  frontend:
    image: trajectopy-frontend:latest
    depends_on:
      - reverse-proxy

  backend:
    image: trajectopy-backend:latest
    depends_on:
      - reverse-proxy

  reverse-proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
