services:
  frontend:
    build: ./trajectopy-react

  backend:
    build: ./trajectopy-api

    volumes:
      - ./data:/app/data

  reverse-proxy:
    image: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
