export const defaultSettings = {
    "ate_in_mm": false,
    "directed_ate": false,
    "matching": "interpolation",
    "similarity_transformation": true,
    "scale_estimation": false,
    "lever_arm_estimation": false,
    "time_shift_estimation": false,
    "sensor_rotation_estimation": false,
    "rpe_enabled": false,
    "rpe_min_distance": 100,
    "rpe_max_distance": 800,
    "rpe_distance_step": 100,
    "rpe_distance_unit": "meter",
    "rpe_use_all_pairs": true,
};